import type { Language } from "./servicesConfig";

type Pair = [string, string];
type HomeCopy = {
  skip: string; brandLabel: string; navLabel: string; nav: [string, string, string]; headerCta: string;
  positioning: { title: string; paragraphs: [string, string, string] };
  method: { title: string; intro: string; steps: Pair[] };
  problems: { title: string; intro: string; link: string; items: Pair[] };
  areas: { title: string; intro: string; items: Pair[] };
  cases: { title: string; intro: string; situation: string; solution: string; result: string; items: { area: string; title: string; situation: string; solution: string; result: string }[] };
  technology: { title: string; intro: string; items: Pair[] };
  invitation: { title: string; text: string; whatsapp: string; meeting: string };
  diagnostic: { title: string; lead: string; text: string; link: string };
  footer: { description: string; location: string; servicesLabel: string; services: [string, string, string]; legalLabel: string; legal: [string, string, string, string] };
};

export const consultingHomeTranslations: Record<Language, HomeCopy> = {
  es: {
    skip: "Saltar al contenido", brandLabel: "UNAiFLY, inicio", navLabel: "Navegación principal", nav: ["Cómo trabajamos", "Qué mejoramos", "Casos de uso"], headerCta: "Analizar mi empresa",
    positioning: { title: "No empezamos por la tecnología. Empezamos por entender tu empresa.", paragraphs: ["Nos sentamos con quienes conocen el trabajo diario. Vemos cómo entra una solicitud, quién la gestiona, dónde se repite trabajo y qué impide avanzar.", "Después proponemos la solución adecuada: simplificar un proceso, automatizar una tarea, conectar herramientas o desarrollar un sistema. La IA entra cuando aporta valor.", "Cada cambio debe responder a una necesidad real del negocio."] },
    method: { title: "Cómo trabajamos", intro: "De entender el problema a comprobar la mejora. Un proceso compartido con tu equipo.", steps: [["Analizamos", "Escuchamos a tu equipo y entendemos cómo trabaja, qué herramientas utiliza y qué objetivos tiene."], ["Detectamos oportunidades", "Identificamos tareas repetitivas, cuellos de botella y mejoras. Priorizamos por impacto y esfuerzo."], ["Diseñamos la solución", "Definimos qué cambiar, cómo hacerlo y con qué indicadores comprobar si funciona."], ["Implementamos", "Conectamos herramientas, automatizamos y ponemos el sistema en marcha con tu equipo."], ["Medimos y mejoramos", "Revisamos tiempos, errores y resultados. Ajustamos la solución a la evolución de tu empresa."]] },
    problems: { title: "¿Te suena alguno de estos problemas?", intro: "El trabajo repetitivo suele parecer parte del día a día. No tiene por qué seguir siéndolo.", link: "Cuéntanos qué está pasando", items: [["Tu equipo pierde horas copiando información entre herramientas.", "Conectamos tus sistemas para que los datos pasen de uno a otro sin volver a introducirlos. Definimos validaciones para detectar errores antes de que se propaguen."], ["Los comerciales hacen seguimiento manual de cada lead.", "Centralizamos los contactos interesados en un CRM, organizamos las oportunidades y automatizamos recordatorios y seguimientos para que el equipo sepa a quién atender y cuándo."], ["Administración repite las mismas tareas cada día.", "Automatizamos la recogida de documentos, el registro de datos y los avisos de aprobación. Tu equipo conserva el control de las decisiones y dedica menos tiempo a tareas mecánicas."], ["Los clientes hacen siempre las mismas preguntas.", "Diseñamos una atención automatizada con información de tu empresa. Resuelve consultas habituales, recoge solicitudes y deriva a una persona cuando necesita ayuda."], ["La información está repartida entre Excel, emails y el CRM.", "Organizamos y centralizamos los datos, eliminamos duplicidades y conectamos las fuentes para que cada persona encuentre la información que necesita."], ["Los responsables no ven con claridad qué ocurre en la empresa.", "Creamos paneles de seguimiento con indicadores de ventas, operaciones y carga de trabajo. Así puedes detectar retrasos y decidir con información actualizada."]] },
    areas: { title: "Áreas que podemos optimizar", intro: "Miramos cada departamento y, sobre todo, lo que ocurre entre ellos.", items: [["Ventas", "Captación, seguimiento y gestión de leads y oportunidades."], ["Administración", "Documentos, registros, aprobaciones y tareas recurrentes."], ["Operaciones", "Coordinación de equipos, pedidos y flujos de trabajo."], ["Atención al cliente", "Consultas, solicitudes y derivación al equipo adecuado."], ["Marketing", "Conexión entre campañas, contactos y seguimiento comercial."], ["Reporting", "Indicadores claros para conocer la evolución del negocio."], ["Gestión de datos", "Información centralizada, ordenada y disponible."], ["Sistemas internos", "Herramientas a medida que se adaptan a tu forma de trabajar."]] },
    cases: { title: "Así se traduce en el día a día", intro: "Ejemplos de aplicación y beneficios esperados. El alcance y los resultados se definen tras analizar cada empresa.", situation: "La situación", solution: "La solución", result: "Qué buscamos mejorar", items: [{ area: "Ventas", title: "Cada oportunidad llega a la persona adecuada.", situation: "Una empresa recibe leads por formularios, email y campañas. Los comerciales los reúnen y persiguen manualmente.", solution: "Centralizamos los leads en el CRM, automatizamos el seguimiento y utilizamos IA para ayudar a priorizar oportunidades.", result: "Menos trabajo manual y mayor velocidad comercial." }, { area: "Administración", title: "Del documento al registro, sin copiar cada dato.", situation: "El equipo recibe facturas por email, copia los datos y pregunta por el estado de cada aprobación.", solution: "Organizamos la entrada de documentos, extraemos la información y conectamos el registro con un circuito de revisión y aprobación.", result: "Menos transcripción y mayor control de los documentos pendientes." }, { area: "Atención al cliente", title: "Las consultas frecuentes dejan espacio a las importantes.", situation: "El equipo responde una y otra vez sobre horarios, servicios o el estado de una solicitud.", solution: "Preparamos un agente de IA con información validada, conectado a los sistemas necesarios y con derivación a una persona.", result: "Respuestas más ágiles y más tiempo para los casos que necesitan atención personal." }, { area: "Operaciones y reporting", title: "Una visión compartida de lo que está pasando.", situation: "Los responsables reúnen hojas de cálculo de varios departamentos para saber qué pedidos van con retraso.", solution: "Conectamos las fuentes de datos, creamos un panel compartido y configuramos avisos ante bloqueos o desviaciones.", result: "Menos preparación de informes y más visibilidad para tomar decisiones." }] },
    technology: { title: "La tecnología adecuada para cada mejora.", intro: "Aprovechamos las herramientas que ya utilizas y añadimos lo que haga falta. Elegimos según el problema, la integración y el uso que hará tu equipo.", items: [["Automatizaciones e integraciones", "Para que las tareas avancen y las herramientas compartan información mediante conexiones y APIs."], ["IA y agentes de IA", "Para interpretar documentos, clasificar solicitudes y asistir al equipo con límites y supervisión definidos."], ["CRM y automatización comercial", "Para centralizar contactos, coordinar el seguimiento y dar continuidad a cada oportunidad."], ["Dashboards y datos", "Para reunir la información y convertirla en indicadores que ayuden a decidir."], ["Sistemas internos a medida", "Para resolver necesidades de gestión que tus herramientas actuales no cubren."], ["Desarrollo web", "Cuando la solución necesita una web, un portal o un formulario conectado a tus procesos y sistemas."]] },
    invitation: { title: "¿Listo para dar el siguiente paso?", text: "Cuéntanos qué necesita tu empresa. Empezamos por entender tus procesos y detectar dónde podemos ayudarte.", whatsapp: "Hablemos por WhatsApp", meeting: "Agenda una reunión" },
    diagnostic: { title: "¿Qué procesos de tu empresa podrían funcionar mejor?", lead: "Analizamos tu situación y detectamos oportunidades de automatización y mejora.", text: "Cuéntanos cómo trabajáis y qué os está quitando tiempo. Empezaremos por entenderlo y valorar dónde tiene sentido actuar.", link: "También puedes reservar una llamada" },
    footer: { description: "Consultoría tecnológica, automatización e IA.\nProcesos y sistemas que ayudan a tu empresa a funcionar mejor.", location: "Barcelona · Trabajamos en remoto en España", servicesLabel: "Más sobre nuestras soluciones", services: ["Digitalización de empresas", "IA aplicada a empresas", "Desarrollo web como parte de tu solución"], legalLabel: "Información legal", legal: ["Aviso legal", "Privacidad", "Términos y condiciones", "Cookies"] },
  },
  en: {
    skip: "Skip to content", brandLabel: "UNAiFLY, home", navLabel: "Main navigation", nav: ["How we work", "What we improve", "Use cases"], headerCta: "Analyse my business",
    positioning: { title: "We don't start with technology. We start by understanding your business.", paragraphs: ["We sit down with the people who know the daily work. We see how a request arrives, who handles it, where work is repeated and what gets in the way.", "Then we propose the right solution: simplify a process, automate a task, connect tools or develop a system. AI comes in when it adds value.", "Every change must respond to a real business need."] },
    method: { title: "How we work", intro: "From understanding the problem to verifying the improvement. A process shared with your team.", steps: [["We analyse", "We listen to your team and understand how it works, which tools it uses and what its goals are."], ["We identify opportunities", "We identify repetitive tasks, bottlenecks and improvements. We prioritise by impact and effort."], ["We design the solution", "We define what to change, how to do it and which indicators will show whether it works."], ["We implement", "We connect tools, automate and launch the system with your team."], ["We measure and improve", "We review time, errors and results. We adapt the solution as your business evolves."]] },
    problems: { title: "Do any of these problems sound familiar?", intro: "Repetitive work often seems like part of everyday life. It doesn't have to stay that way.", link: "Tell us what's happening", items: [["Your team spends hours copying information between tools.", "We connect your systems so data moves between them without being entered again. We define checks to detect errors before they spread."], ["Your sales team follows up every lead manually.", "We centralise interested contacts in a CRM, organise opportunities and automate reminders and follow-ups so the team knows who to assist and when."], ["Administration repeats the same tasks every day.", "We automate document collection, data entry and approval notifications. Your team keeps control of decisions and spends less time on mechanical tasks."], ["Customers always ask the same questions.", "We design automated support using your business information. It answers common questions, collects requests and hands over to a person when help is needed."], ["Information is scattered across Excel, emails and the CRM.", "We organise and centralise data, remove duplicates and connect sources so everyone can find the information they need."], ["Managers can't clearly see what is happening in the business.", "We create monitoring dashboards with sales, operations and workload indicators, helping you spot delays and decide with up-to-date information."]] },
    areas: { title: "Areas we can optimise", intro: "We look at every department and, above all, what happens between them.", items: [["Sales", "Lead and opportunity acquisition, follow-up and management."], ["Administration", "Documents, records, approvals and recurring tasks."], ["Operations", "Team coordination, orders and workflows."], ["Customer service", "Queries, requests and routing to the right team."], ["Marketing", "Connecting campaigns, contacts and sales follow-up."], ["Reporting", "Clear indicators to understand business performance."], ["Data management", "Centralised, organised and available information."], ["Internal systems", "Custom tools that adapt to the way you work."]] },
    cases: { title: "What this looks like day to day", intro: "Examples of applications and expected benefits. Scope and results are defined after analysing each business.", situation: "The situation", solution: "The solution", result: "What we aim to improve", items: [{ area: "Sales", title: "Every opportunity reaches the right person.", situation: "A business receives leads through forms, email and campaigns. Salespeople gather and chase them manually.", solution: "We centralise leads in the CRM, automate follow-up and use AI to help prioritise opportunities.", result: "Less manual work and faster sales response." }, { area: "Administration", title: "From document to record, without copying every field.", situation: "The team receives invoices by email, copies the data and asks about each approval status.", solution: "We organise incoming documents, extract information and connect the record to a review and approval workflow.", result: "Less transcription and greater control over pending documents." }, { area: "Customer service", title: "Common questions leave room for important ones.", situation: "The team repeatedly answers questions about opening hours, services or request status.", solution: "We prepare an AI agent with verified information, connected to the required systems and able to hand over to a person.", result: "Faster answers and more time for cases needing personal attention." }, { area: "Operations and reporting", title: "A shared view of what is happening.", situation: "Managers combine spreadsheets from several departments to find out which orders are delayed.", solution: "We connect data sources, create a shared dashboard and configure alerts for blocks or deviations.", result: "Less report preparation and more visibility for decision-making." }] },
    technology: { title: "The right technology for every improvement.", intro: "We make the most of the tools you already use and add what is needed. We choose based on the problem, integration and how your team will use it.", items: [["Automation and integrations", "So tasks move forward and tools share information through connections and APIs."], ["AI and AI agents", "To interpret documents, classify requests and assist the team with defined limits and supervision."], ["CRM and sales automation", "To centralise contacts, coordinate follow-up and maintain continuity for every opportunity."], ["Dashboards and data", "To bring information together and turn it into indicators that support decisions."], ["Custom internal systems", "To solve management needs your current tools do not cover."], ["Web development", "When the solution needs a website, portal or form connected to your processes and systems."]] },
    invitation: { title: "Ready to take the next step?", text: "Tell us what your business needs. We start by understanding your processes and identifying where we can help.", whatsapp: "Let's talk on WhatsApp", meeting: "Schedule a meeting" },
    diagnostic: { title: "Which processes in your business could work better?", lead: "We analyse your situation and identify opportunities for automation and improvement.", text: "Tell us how you work and what is taking up your time. We'll begin by understanding it and assessing where action makes sense.", link: "You can also book a call" },
    footer: { description: "Technology consulting, automation and AI.\nProcesses and systems that help your business work better.", location: "Barcelona · We work remotely across Spain", servicesLabel: "More about our solutions", services: ["Business digitalisation", "AI applied to business", "Web development as part of your solution"], legalLabel: "Legal information", legal: ["Legal notice", "Privacy", "Terms and conditions", "Cookies"] },
  },
  ca: {
    skip: "Saltar al contingut", brandLabel: "UNAiFLY, inici", navLabel: "Navegació principal", nav: ["Com treballem", "Què millorem", "Casos d'ús"], headerCta: "Analitzar la meva empresa",
    positioning: { title: "No comencem per la tecnologia. Comencem per entendre la teva empresa.", paragraphs: ["Ens asseiem amb les persones que coneixen la feina diària. Veiem com entra una sol·licitud, qui la gestiona, on es repeteix feina i què impedeix avançar.", "Després proposem la solució adequada: simplificar un procés, automatitzar una tasca, connectar eines o desenvolupar un sistema. La IA entra quan aporta valor.", "Cada canvi ha de respondre a una necessitat real del negoci."] },
    method: { title: "Com treballem", intro: "D'entendre el problema a comprovar la millora. Un procés compartit amb el teu equip.", steps: [["Analitzem", "Escoltem el teu equip i entenem com treballa, quines eines utilitza i quins objectius té."], ["Detectem oportunitats", "Identifiquem tasques repetitives, colls d'ampolla i millores. Prioritzem per impacte i esforç."], ["Dissenyem la solució", "Definim què canviar, com fer-ho i amb quins indicadors comprovar si funciona."], ["Implementem", "Connectem eines, automatitzem i posem el sistema en marxa amb el teu equip."], ["Mesurem i millorem", "Revisem temps, errors i resultats. Ajustem la solució a l'evolució de la teva empresa."]] },
    problems: { title: "Et sona algun d'aquests problemes?", intro: "La feina repetitiva sovint sembla part del dia a dia. No ha de continuar sent així.", link: "Explica'ns què està passant", items: [["El teu equip perd hores copiant informació entre eines.", "Connectem els teus sistemes perquè les dades passin d'un a l'altre sense tornar a introduir-les. Definim validacions per detectar errors abans que es propaguin."], ["Els comercials fan el seguiment manual de cada lead.", "Centralitzem els contactes interessats en un CRM, organitzem les oportunitats i automatitzem recordatoris i seguiments."], ["Administració repeteix les mateixes tasques cada dia.", "Automatitzem la recollida de documents, el registre de dades i els avisos d'aprovació. El teu equip conserva el control i dedica menys temps a tasques mecàniques."], ["Els clients fan sempre les mateixes preguntes.", "Dissenyem una atenció automatitzada amb informació de la teva empresa. Resol consultes habituals, recull sol·licituds i deriva a una persona quan cal."], ["La informació està repartida entre Excel, correus i el CRM.", "Organitzem i centralitzem les dades, eliminem duplicitats i connectem les fonts perquè tothom trobi la informació que necessita."], ["Els responsables no veuen amb claredat què passa a l'empresa.", "Creem quadres de seguiment amb indicadors de vendes, operacions i càrrega de feina per detectar retards i decidir amb informació actualitzada."]] },
    areas: { title: "Àrees que podem optimitzar", intro: "Mirem cada departament i, sobretot, què passa entre ells.", items: [["Vendes", "Captació, seguiment i gestió de leads i oportunitats."], ["Administració", "Documents, registres, aprovacions i tasques recurrents."], ["Operacions", "Coordinació d'equips, comandes i fluxos de treball."], ["Atenció al client", "Consultes, sol·licituds i derivació a l'equip adequat."], ["Màrqueting", "Connexió entre campanyes, contactes i seguiment comercial."], ["Reporting", "Indicadors clars per conèixer l'evolució del negoci."], ["Gestió de dades", "Informació centralitzada, ordenada i disponible."], ["Sistemes interns", "Eines a mida que s'adapten a la teva manera de treballar."]] },
    cases: { title: "Així es tradueix en el dia a dia", intro: "Exemples d'aplicació i beneficis esperats. L'abast i els resultats es defineixen després d'analitzar cada empresa.", situation: "La situació", solution: "La solució", result: "Què busquem millorar", items: [{ area: "Vendes", title: "Cada oportunitat arriba a la persona adequada.", situation: "Una empresa rep leads per formularis, correu i campanyes. Els comercials els reuneixen i persegueixen manualment.", solution: "Centralitzem els leads al CRM, automatitzem el seguiment i utilitzem IA per ajudar a prioritzar oportunitats.", result: "Menys feina manual i més velocitat comercial." }, { area: "Administració", title: "Del document al registre, sense copiar cada dada.", situation: "L'equip rep factures per correu, copia les dades i pregunta per l'estat de cada aprovació.", solution: "Organitzem l'entrada de documents, n'extraiem la informació i connectem el registre amb un circuit de revisió i aprovació.", result: "Menys transcripció i més control dels documents pendents." }, { area: "Atenció al client", title: "Les consultes freqüents deixen espai a les importants.", situation: "L'equip respon una vegada i una altra sobre horaris, serveis o l'estat d'una sol·licitud.", solution: "Preparem un agent d'IA amb informació validada, connectat als sistemes necessaris i amb derivació a una persona.", result: "Respostes més àgils i més temps per als casos que necessiten atenció personal." }, { area: "Operacions i reporting", title: "Una visió compartida del que està passant.", situation: "Els responsables reuneixen fulls de càlcul de diversos departaments per saber quines comandes van amb retard.", solution: "Connectem les fonts de dades, creem un quadre compartit i configurem avisos davant bloquejos o desviacions.", result: "Menys preparació d'informes i més visibilitat per prendre decisions." }] },
    technology: { title: "La tecnologia adequada per a cada millora.", intro: "Aprofitem les eines que ja utilitzes i afegim el que calgui. Triem segons el problema, la integració i l'ús que en farà el teu equip.", items: [["Automatitzacions i integracions", "Perquè les tasques avancin i les eines comparteixin informació mitjançant connexions i APIs."], ["IA i agents d'IA", "Per interpretar documents, classificar sol·licituds i assistir l'equip amb límits i supervisió definits."], ["CRM i automatització comercial", "Per centralitzar contactes, coordinar el seguiment i donar continuïtat a cada oportunitat."], ["Quadres de comandament i dades", "Per reunir la informació i convertir-la en indicadors que ajudin a decidir."], ["Sistemes interns a mida", "Per resoldre necessitats de gestió que les eines actuals no cobreixen."], ["Desenvolupament web", "Quan la solució necessita una web, un portal o un formulari connectat als teus processos i sistemes."]] },
    invitation: { title: "Preparat per fer el següent pas?", text: "Explica'ns què necessita la teva empresa. Comencem per entendre els teus processos i detectar on podem ajudar.", whatsapp: "Parlem per WhatsApp", meeting: "Agenda una reunió" },
    diagnostic: { title: "Quins processos de la teva empresa podrien funcionar millor?", lead: "Analitzem la teva situació i detectem oportunitats d'automatització i millora.", text: "Explica'ns com treballeu i què us està traient temps. Començarem per entendre-ho i valorar on té sentit actuar.", link: "També pots reservar una trucada" },
    footer: { description: "Consultoria tecnològica, automatització i IA.\nProcessos i sistemes que ajuden la teva empresa a funcionar millor.", location: "Barcelona · Treballem en remot a Espanya", servicesLabel: "Més sobre les nostres solucions", services: ["Digitalització d'empreses", "IA aplicada a empreses", "Desenvolupament web com a part de la teva solució"], legalLabel: "Informació legal", legal: ["Avís legal", "Privacitat", "Termes i condicions", "Cookies"] },
  },
  it: {
    skip: "Vai al contenuto", brandLabel: "UNAiFLY, home", navLabel: "Navigazione principale", nav: ["Come lavoriamo", "Cosa miglioriamo", "Casi d'uso"], headerCta: "Analizza la mia azienda",
    positioning: { title: "Non partiamo dalla tecnologia. Partiamo dalla comprensione della tua azienda.", paragraphs: ["Ci sediamo con chi conosce il lavoro quotidiano. Vediamo come arriva una richiesta, chi la gestisce, dove si ripete il lavoro e cosa impedisce di avanzare.", "Poi proponiamo la soluzione adatta: semplificare un processo, automatizzare un'attività, collegare strumenti o sviluppare un sistema. L'IA entra quando crea valore.", "Ogni cambiamento deve rispondere a una reale esigenza aziendale."] },
    method: { title: "Come lavoriamo", intro: "Dalla comprensione del problema alla verifica del miglioramento. Un processo condiviso con il tuo team.", steps: [["Analizziamo", "Ascoltiamo il tuo team e capiamo come lavora, quali strumenti usa e quali obiettivi ha."], ["Individuiamo opportunità", "Identifichiamo attività ripetitive, colli di bottiglia e miglioramenti. Diamo priorità in base a impatto e sforzo."], ["Progettiamo la soluzione", "Definiamo cosa cambiare, come farlo e con quali indicatori verificarne il funzionamento."], ["Implementiamo", "Colleghiamo gli strumenti, automatizziamo e avviamo il sistema con il tuo team."], ["Misuriamo e miglioriamo", "Esaminiamo tempi, errori e risultati. Adattiamo la soluzione all'evoluzione della tua azienda."]] },
    problems: { title: "Riconosci uno di questi problemi?", intro: "Il lavoro ripetitivo sembra spesso parte della quotidianità. Non deve restare così.", link: "Raccontaci cosa sta succedendo", items: [["Il tuo team perde ore a copiare informazioni tra gli strumenti.", "Colleghiamo i sistemi affinché i dati passino dall'uno all'altro senza essere reinseriti. Definiamo controlli per rilevare gli errori prima che si propaghino."], ["I commerciali seguono manualmente ogni lead.", "Centralizziamo i contatti interessati in un CRM, organizziamo le opportunità e automatizziamo promemoria e follow-up."], ["L'amministrazione ripete le stesse attività ogni giorno.", "Automatizziamo la raccolta dei documenti, la registrazione dei dati e gli avvisi di approvazione. Il team mantiene il controllo e dedica meno tempo alle attività meccaniche."], ["I clienti fanno sempre le stesse domande.", "Progettiamo un'assistenza automatizzata con le informazioni della tua azienda. Risponde alle domande comuni, raccoglie richieste e passa a una persona quando serve."], ["Le informazioni sono sparse tra Excel, email e CRM.", "Organizziamo e centralizziamo i dati, eliminiamo i duplicati e colleghiamo le fonti affinché tutti trovino le informazioni necessarie."], ["I responsabili non vedono chiaramente cosa accade in azienda.", "Creiamo dashboard con indicatori di vendita, operazioni e carico di lavoro per individuare ritardi e decidere con informazioni aggiornate."]] },
    areas: { title: "Aree che possiamo ottimizzare", intro: "Guardiamo ogni reparto e, soprattutto, ciò che accade tra loro.", items: [["Vendite", "Acquisizione, follow-up e gestione di lead e opportunità."], ["Amministrazione", "Documenti, registri, approvazioni e attività ricorrenti."], ["Operazioni", "Coordinamento dei team, ordini e flussi di lavoro."], ["Assistenza clienti", "Richieste e indirizzamento al team giusto."], ["Marketing", "Collegamento tra campagne, contatti e follow-up commerciale."], ["Reporting", "Indicatori chiari per conoscere l'andamento aziendale."], ["Gestione dei dati", "Informazioni centralizzate, ordinate e disponibili."], ["Sistemi interni", "Strumenti su misura che si adattano al tuo modo di lavorare."]] },
    cases: { title: "Come si traduce nel lavoro quotidiano", intro: "Esempi di applicazione e benefici attesi. Ambito e risultati vengono definiti dopo aver analizzato ogni azienda.", situation: "La situazione", solution: "La soluzione", result: "Cosa vogliamo migliorare", items: [{ area: "Vendite", title: "Ogni opportunità arriva alla persona giusta.", situation: "Un'azienda riceve lead da moduli, email e campagne. I commerciali li raccolgono e li seguono manualmente.", solution: "Centralizziamo i lead nel CRM, automatizziamo il follow-up e usiamo l'IA per aiutare a dare priorità alle opportunità.", result: "Meno lavoro manuale e maggiore velocità commerciale." }, { area: "Amministrazione", title: "Dal documento al registro, senza copiare ogni dato.", situation: "Il team riceve fatture via email, copia i dati e chiede lo stato di ogni approvazione.", solution: "Organizziamo l'ingresso dei documenti, estraiamo le informazioni e colleghiamo il registro a un flusso di revisione e approvazione.", result: "Meno trascrizione e maggiore controllo sui documenti in sospeso." }, { area: "Assistenza clienti", title: "Le domande frequenti lasciano spazio a quelle importanti.", situation: "Il team risponde continuamente su orari, servizi o stato di una richiesta.", solution: "Prepariamo un agente IA con informazioni verificate, collegato ai sistemi necessari e con passaggio a una persona.", result: "Risposte più rapide e più tempo per i casi che richiedono attenzione personale." }, { area: "Operazioni e reporting", title: "Una visione condivisa di ciò che accade.", situation: "I responsabili riuniscono fogli di calcolo di vari reparti per sapere quali ordini sono in ritardo.", solution: "Colleghiamo le fonti dati, creiamo una dashboard condivisa e configuriamo avvisi per blocchi o scostamenti.", result: "Meno preparazione dei report e più visibilità per decidere." }] },
    technology: { title: "La tecnologia giusta per ogni miglioramento.", intro: "Sfruttiamo gli strumenti che già utilizzi e aggiungiamo ciò che serve. Scegliamo in base al problema, all'integrazione e all'uso che ne farà il tuo team.", items: [["Automazioni e integrazioni", "Per far avanzare le attività e condividere informazioni tra strumenti tramite connessioni e API."], ["IA e agenti IA", "Per interpretare documenti, classificare richieste e assistere il team con limiti e supervisione definiti."], ["CRM e automazione commerciale", "Per centralizzare i contatti, coordinare il follow-up e dare continuità a ogni opportunità."], ["Dashboard e dati", "Per riunire le informazioni e trasformarle in indicatori utili alle decisioni."], ["Sistemi interni su misura", "Per risolvere esigenze gestionali che gli strumenti attuali non coprono."], ["Sviluppo web", "Quando la soluzione richiede un sito, un portale o un modulo collegato ai tuoi processi e sistemi."]] },
    invitation: { title: "Pronto per il prossimo passo?", text: "Raccontaci di cosa ha bisogno la tua azienda. Partiamo dalla comprensione dei processi e individuiamo dove possiamo aiutarti.", whatsapp: "Parliamo su WhatsApp", meeting: "Fissa un incontro" },
    diagnostic: { title: "Quali processi della tua azienda potrebbero funzionare meglio?", lead: "Analizziamo la tua situazione e individuiamo opportunità di automazione e miglioramento.", text: "Raccontaci come lavorate e cosa vi porta via tempo. Inizieremo capendolo e valutando dove ha senso intervenire.", link: "Puoi anche prenotare una chiamata" },
    footer: { description: "Consulenza tecnologica, automazione e IA.\nProcessi e sistemi che aiutano la tua azienda a funzionare meglio.", location: "Barcellona · Lavoriamo da remoto in Spagna", servicesLabel: "Scopri le nostre soluzioni", services: ["Digitalizzazione aziendale", "IA applicata alle aziende", "Sviluppo web come parte della tua soluzione"], legalLabel: "Informazioni legali", legal: ["Note legali", "Privacy", "Termini e condizioni", "Cookie"] },
  },
};
